name: Projects jobs

on:
  push:
    branches: [ "ref-step-3" ]
  pull_request:
    branches: [ "ref-step-3" ]

jobs:
  build-test-lint:
    name: Build + Test + Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v1.3.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          checkstyle_config: google_checks.xml
          fail_on_error: true

      - name: Build with Maven
        run: mvn -B package --file is_sem_work/backend/pom.xml

      - name: Run tests
        run: mvn -B test --file is_sem_work/backend/pom.xml

  security:
    name: CodeQL Security Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

